version: '3'

services:
  app-dcd:
    build:
      context: .
      args:
        - CONFIGURATION=$APP_DCD_CONFIGURATION
    container_name: app-dcd
    environment:
     - NGINX_HOST=$APP_DCD_HOST
     - NGINX_PORT=$APP_DCD_PORT
    restart: on-failure

  envoy:
    image: envoyproxy/envoy-alpine:v1.19-latest
    container_name: envoy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./certs:/etc/certs
    environment:
     - PASSPHRASE=$PASSPHRASE
    networks:
      - dcd-net

networks:
  dcd-net:
    external: true